id: app
title: Starter Java Application
type: project
version: 0.1.4
icon: app.png

catalog:
  category: Web Applications
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.3.0
  source_url: https://github.com/GovReady/starter_java_applicaiton/tree/master/apps/starter_java_application
  description:
    short: |
      Start files for a Java web application
    long: |
      Start files for a Java web application
  recommended_for:
    - key_short: Org
      value: Large
    - key_short: Tech
      value: Sophisticated
    - key_short: Role
      value: PM

questions:
  - id: fisma_system_categorization
    title: System Categorization
    type: module
    protocol: govready.com/apps/compliance/2018/fisma/system-categorization

# Technologies
  - id: web_server
    title: Web Server
    type: module
    protocol: web_server

  - id: infrastructure
    title: Infrastructure
    type: module
    protocol: opencontrol

  - id: java_application_server
    title: Java Application Server
    type: module
    protocol: java_application_server
    
  - id: unix_server
    title: Unix Server
    type: module
    protocol: unix_server

  - id: database
    title: Database
    type: module
    protocol: database

# Policy documents
  - id: sm_policy_privacy
    title: Privacy Policy
    type: module
    protocol: sm_policy_privacy

# People
  - id: fed_poc_pm
    title: PM
    type: module
    protocol: fed_poc_pm
    icon: person-3.png

  - id: fed_poc_developer
    title: Developer
    type: module
    protocol: fed_poc_developer
    icon: person-3.png

  - id: fed_poc_issm
    title: ISSM
    type: module
    protocol: fed_poc_issm
    icon: person-3.png

  - id: fed_poc_isso
    title: ISSO
    type: module
    protocol: fed_poc_isso
    icon: person-3.png

  - id: fed_poc_ao
    title: AO
    type: module
    protocol: fed_poc_ao
    icon: person-3.png

# Artifacts
  - id: ssp
    title: View Simple SSP
    type: module
    module-id: ssp
    icon: checkmark.png
    placement: action-buttons

  - id: ssp2
    title: View FISMA-Style SSP
    type: module
    module-id: ssp2
    icon: checkmark.png
    placement: action-buttons
